name: Build and Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ GToolkit64-release ]
    name: ${{ matrix.smalltalk }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Required to enable the registerInIceberg option.
          # We need to fetch all of the commits because Iceberg always creates a full history.
          fetch-depth: 0
      
      # Setup SmalltalkCI
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          
      # Loads Smalltalk image with project code and run the tests
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
        
      # Load knowledge database
      - name: Load knowledge database
        run: |
          lsb_release -a
          xvfb-run -a firefox -v
          xvfb-run -a bash -c '/home/runner/.smalltalkCI/_builds/bin/GlamorousToolkit-cli --interactive /home/runner/.smalltalkCI/_builds/TravisCI.image -- help'
          echo "Trying xvfb-run:"
          xvfb-run -a /home/runner/.smalltalkCI/_builds/bin/GlamorousToolkit-cli --interactive /home/runner/.smalltalkCI/_builds/TravisCI.image -- st --save --quit /home/runner/work/gtoolkit-ci-experiment/gtoolkit-ci-experiment/ci/scripts/loadKnowledge.st

      # Upload the Pharo image artifact
      - name: Upload Pharo image
        uses: actions/upload-artifact@v3
        with:
          name: PharoCIExperiment.image
          path: /home/runner/.smalltalkCI/_builds/TravisCI.image
          retention-days: 14 days
     
      # Upload coverage data
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
