name: Build and Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ GToolkit64-release ]
    name: ${{ matrix.smalltalk }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Required to enable the registerInIceberg option.
          # We need to fetch all of the commits because Iceberg always creates a full history.
          fetch-depth: 0
      
      # Setup SmalltalkCI
      - name: Setup SmalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          
      # Loads Smalltalk image with project code and run the tests
      - name: Load Image and Run Tests
        run: smalltalkci -v -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
        
      # Load knowledge database
      - name: Load knowledge database
        run: |
          echo "Downloading Glamorous Toolkit:"
          curl --fail --silent --show-error --location --retry 3 --retry-delay 5 --max-time 300 -o /home/runner/.smalltalkCI/_cache/GlamorousToolkit-Linux-x86_64-v0.8.2944.zip https://github.com/feenkcom/gtoolkit/releases/download/v0.8.2944/GlamorousToolkit-Linux-x86_64-v0.8.2944.zip
          echo "Inflating Glamorous Toolkit:"
          unzip /home/runner/.smalltalkCI/_cache/GlamorousToolkit-Linux-x86_64-v0.8.2944.zip -d  /home/runner/.smalltalkCI/_cache
          #sudo apt-get update -y
          sudo apt-get install -y libegl-dev
          #ldd /home/runner/.smalltalkCI/_cache/lib/libSkia.so
          xvfb-run -a /home/runner/.smalltalkCI/_cache/bin/GlamorousToolkit-cli --interactive /home/runner/.smalltalkCI/_cache/GlamorousToolkit.image st --save --quit /home/runner/work/gtoolkit-lepiter-ci/gtoolkit-lepiter-ci/ci/scripts/loadKnowledge.st
          #export DISPLAY=:99.0
          #Xvfb $DISPLAY -screen 0 1024x768x16 & /home/runner/.smalltalkCI/_cache/bin/GlamorousToolkit-cli --interactive /home/runner/.smalltalkCI/_cache/GlamorousToolkit.image st --quit /home/runner/work/gtoolkit-lepiter-ci/gtoolkit-lepiter-ci/ci/scripts/loadKnowledge.st

      # Run examples
      - name: Run examples
        run:  |
            /home/runner/.smalltalkCI/_cache/bin/GlamorousToolkit-cli /home/runner/.smalltalkCI/_cache/GlamorousToolkit.image examples --junit-xml-output --fail-on-failure LepiterDefinitions
            mv ${{ github.workspace }}/progress-examples.log ${{ github.workspace }}/*-Examples.xml /home/runner/.smalltalkCI/_cache/

      # Export knowledge base
      - name: Export knowledge base
        run: |
            cp -R /home/runner/.smalltalkCI/_cache/gt-extra/feenkcom /home/runner/.smalltalkCI/_cache/pharo-local/iceberg
            xvfb-run -a /home/runner/.smalltalkCI/_cache/bin/GlamorousToolkit-cli --interactive /home/runner/.smalltalkCI/_cache/GlamorousToolkit.image st --save  --quit /home/runner/work/gtoolkit-lepiter-ci/gtoolkit-lepiter-ci/ci/scripts/exportKnowledge.st
            cp -R ${{ github.workspace }}/public /home/runner/.smalltalkCI/_cache

      # Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PharoCIExperiment_build-${{ github.run_number }}
          path: |
              /home/runner/.smalltalkCI/_cache/GlamorousToolkit.image
              /home/runner/.smalltalkCI/_cache/GlamorousToolkit.changes
              /home/runner/.smalltalkCI/_cache/pharo-local/lepiter
              /home/runner/.smalltalkCI/_cache/pharo-local/iceberg/blueplanelabs
              /home/runner/.smalltalkCI/_cache/progress-examples.log
              /home/runner/.smalltalkCI/_cache/*-Examples.xml
              /home/runner/.smalltalkCI/_cache/public
     
      # Upload coverage data
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Publishes knowledge base export
      - name: Publishes knowledge base export
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
